# Generated by Django 3.0.3 on 2020-07-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='contact',
            field=models.CharField(max_length=13),
        ),
    ]
